name: Kymirrorstudios
favicon: null
layout_spectrum: 0.51122
typography_spectrum: 0.48743838467635214
title: Kymirror Studios
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2b0082'
    - '#c5c5c5'
    - '#9e9e9e'
    - '#462a81'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.5450670218560845
  rhythmicContrast: 0.5
purpose: []
